# Generated by Django 2.2 on 2020-01-24 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_profilefeeditems'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProfileFeedItems',
            new_name='ProfileFeedItem',
        ),
    ]
